# ─────────────────────────────────────────────────────────────────────────────
# GMix proxy opengl32.dll — .def generator.
#
# The proxy DLL must export every symbol real opengl32.dll exports (games
# import hundreds of GL1.1-era entry points directly by name), but we only
# WANT to intercept one (wglSwapBuffers). Hand-typing ~400 forward lines is
# both tedious and error-prone, so this script generates them at build time
# from the real system opengl32.dll's own export table via `dumpbin /exports`
# (part of the MSVC toolchain -- run from a Developer Command/PowerShell
# Prompt so it's on PATH; CMakeLists.txt locates it explicitly if not).
#
# Forward target: "opengl32_orig.<Name>", NOT "opengl32.<Name>". If the
# forwards pointed at "opengl32", the loader would resolve that bare name via
# normal DLL search order -- which finds OUR OWN proxy first (that's the
# entire point of dropping a same-named DLL next to the game's exe), causing
# infinite self-referential forwarding instead of reaching the real driver
# DLL. `gmix.exe --install-proxy` (see src/cli.cpp) copies the real system
# opengl32.dll to "opengl32_orig.dll" alongside the proxy for exactly this
# reason -- both files must be present in the game's directory for the proxy
# to function.
#
# Usage: generate_def.ps1 -OutFile <path\opengl32_proxy.generated.def>
#                          -Overridden wglSwapBuffers[,other,names]
# ─────────────────────────────────────────────────────────────────────────────
param(
    [Parameter(Mandatory=$true)][string]$OutFile,
    [string[]]$Overridden = @("wglSwapBuffers")
)

$sysDll = Join-Path $env:WINDIR "System32\opengl32.dll"
if (-not (Test-Path $sysDll)) {
    Write-Error "generate_def.ps1: real opengl32.dll not found at $sysDll"
    exit 1
}

$dumpbin = (Get-Command dumpbin.exe -ErrorAction SilentlyContinue)
if (-not $dumpbin) {
    Write-Error "generate_def.ps1: dumpbin.exe not on PATH -- run from a Visual Studio Developer PowerShell"
    exit 1
}

$exportsRaw = & dumpbin.exe /exports $sysDll
# dumpbin export table lines look like:
#     1    0 0001A2B0 glAccum
# Column layout is whitespace-separated: ordinal, hint, RVA, name (name may be
# absent for pure-ordinal exports, which real opengl32.dll doesn't have).
$names = New-Object System.Collections.Generic.List[string]
foreach ($line in $exportsRaw) {
    if ($line -match '^\s*\d+\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+([A-Za-z_][A-Za-z0-9_]*)\s*$') {
        $names.Add($Matches[1])
    }
}
if ($names.Count -eq 0) {
    Write-Error "generate_def.ps1: parsed zero exports from $sysDll -- dumpbin output format may have changed"
    exit 1
}

# NOT `New-Object System.Collections.Generic.HashSet[string]($Overridden)` --
# with a single-element array, PowerShell's New-Object overload resolution
# picks the HashSet(int capacity) constructor instead of HashSet(IEnumerable),
# and fails trying to convert the element to an int. A plain hashtable used
# as a set (via ContainsKey) sidesteps the overload ambiguity entirely.
$overriddenSet = @{}
foreach ($n in $Overridden) { $overriddenSet[$n] = $true }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("; Auto-generated by generate_def.ps1 -- do not edit by hand.")
$lines.Add("; Forwards every real opengl32.dll export except: $($Overridden -join ', ')")
$lines.Add("LIBRARY opengl32")
$lines.Add("EXPORTS")
# Our own real implementations first (plain export -- resolves to the
# matching extern "C" symbol in opengl32_proxy.obj), then every passthrough
# forward.
foreach ($n in $Overridden) {
    $lines.Add("    $n")
}
foreach ($n in $names) {
    if ($overriddenSet.ContainsKey($n)) { continue }
    $lines.Add("    $n = opengl32_orig.$n")
}
Set-Content -Path $OutFile -Value $lines -Encoding ASCII
Write-Host "generate_def.ps1: wrote $($names.Count - $overriddenSet.Count) forwards to $OutFile"
